### ISSUE TITLE
CMathOOo pour Libre Office 6

### ISSUE THREAD

**Issue by samuelortion** [cdevalland/CmathOOo#1]
Bonjour,
J'ai récemment mis à jour Libre Office sur Windows, et CMathOOo ne semble pas fonctionner avec cette version. 
F9 renvoie vers le code basic et retourne une erreur 

```
Erreur de syntaxe BASIC.

La variable hachures est déjà définie.
```
**Détail des conditions :**
OS : Windows 7
Version de CMathOOo: 2013.10.29
Version de Libre Office: 6.4.2.2 (x64) 

Je ne sais pas si vous supporter encore ce projet...

Cordialement, 
Samuel ORTION,
Lycéen et fils d'une prof de math utilisant CMathOOo ;)

**Comment by cdevalland** [comment]
Bonjour,
effectivement, j'ai reproduit le problème après avoir installé la dernière
version sous linux.
Je vais proposer une mise à jour.
En attendant, remplacez dans la procédure "Hachures" le nom de variable
"hachures" par "mhachures" et cela suffira.
Cela commence à la ligne 117 et termine à la ligne 154 (6 remplacements en
tout).
Dites-moi si c'est bon.

Le mar. 31 mars 2020 à 15:19, OrnithOrtion <notifications@github.com> a
écrit :
